HolaSombreros/SEP6

src/MovieManagement.Domain/Models/ListType.cs
src/MovieManagement.Domain/Models/MovieList.cs
src/MovieManagement.TMDB.Api/Config/ApiConfig.cs
src/MovieManagement.TMDB.Api/Dtos/ListType.cs
src/MovieManagement.TMDB.Api/Dtos/MovieDto.cs
src/MovieManagement.TMDB.Api/Mappers/MovieMapper.cs
src/MovieManagement.TMDB.Api/Services/IMovieService.cs
src/MovieManagement.TMDB.Api/Services/MovieService.cs
src/MovieManagement/appsettings.json
test/MovieManagement.Test/MovieTests/MovieServiceTests.cs

Updated list of movies with Popular, Top Rated, Upcoming and In Theatre
https://via-group2.atlassian.net/browse/SEP6-10

Sep6 10 be view list of movies

---

src/MovieManagement/Pages/User/Account.razor
src/MovieManagement/Pages/User/Account.razor.cs
src/MovieManagement/Shared/NavMenu.razor

SEP6-39: View account

---

.gitignore
MovieManagement.sln
src/MovieManagement.TMDB.Api/Config/ApiConfig.cs
src/MovieManagement.TMDB.Api/Services/Service.cs
src/MovieManagement/Components/MovieCard.razor.cs
src/MovieManagement/Components/MovieCard.razor.css
src/MovieManagement/Pages/MovieDetails/MovieDetails.razor
src/MovieManagement/Pages/MovieDetails/MovieDetails.razor.cs
src/MovieManagement/Program.cs
src/MovieManagement/ViewModels/Index/MovieViewModel.cs
src/MovieManagement/appsettings.json

SEP6-79 Fix issue regarding fetching of data from external API

---

src/MovieManagement.Database/Context/MovieManagementDbContext.cs
src/MovieManagement.Database/Entities/MovieListEntity.cs
src/MovieManagement.Database/Entities/MovieListMovieEntity.cs
src/MovieManagement.Database/Entities/RatingEntity.cs
src/MovieManagement.Database/Repositories/IRatingRepository.cs
src/MovieManagement.Database/Repositories/RatingRepository.cs
src/MovieManagement.Domain/Models/TMDB/Person.cs
src/MovieManagement.Domain/Models/TMDB/ProductionCompany.cs
src/MovieManagement.Domain/Models/TMDB/ProductionCountry.cs
src/MovieManagement.Domain/Models/TMDB/SpokenLanguage.cs
src/MovieManagement.Domain/Models/Visitor.cs
src/MovieManagement.Functions/Dtos/RatingQueryDto.cs
src/MovieManagement.Functions/Dtos/RatingSubsetDto.cs
src/MovieManagement.Functions/GlobalUsings.cs
src/MovieManagement.Functions/Mappers/MapperProfile.cs
src/MovieManagement.Functions/Movie/RateFunction.cs
src/MovieManagement.Functions/Services/IRatingService.cs
src/MovieManagement.Functions/Services/RatingService.cs
src/MovieManagement.Functions/Validators/RatingDtoValidator.cs

View Ratings by movie ids Function
If you add an id that does not exist in the database, it will ignore it
https://via-group2.atlassian.net/browse/SEP6-32

SEP6-32: GetMovieRatings by ids function

---

.github/workflows/main_moviemanagementfunctions.yml
src/MovieManagement.Database/Entities/UserEntity.cs
src/MovieManagement.Database/Repositories/UserRepository.cs
src/MovieManagement.Functions/Dtos/DeleteUserDto.cs
src/MovieManagement.Functions/GlobalUsings.cs
src/MovieManagement.Functions/Services/UserService.cs
src/MovieManagement.Functions/Users/DeleteUser.cs
src/MovieManagement.Functions/Users/EditUser.cs
src/MovieManagement.Functions/Validators/UserDtoValidator.cs
src/MovieManagement.TMDB.Api/Services/SearchService.cs
src/MovieManagement/Services/AzureService.cs
src/MovieManagement/Services/IAzureService.cs

Function to update user
A function to update the details of a user and refactor delete user function
delete user
update user

Sep-6: 76 edit account function

---

src/MovieManagement/Pages/User/Account.razor.cs
src/MovieManagement/Services/AzureService.cs
src/MovieManagement/Services/UserService.cs
src/MovieManagement/appsettings.json

SEP6-76: Edit FE calls for user edit and delete

---

src/MovieManagement.Functions/Ratings/AddRating.cs

SEP6-24: Added logs in AddRating

---

src/MovieManagement.TMDB.Api/Services/IPersonService.cs
src/MovieManagement.TMDB.Api/Services/ISearchService.cs
src/MovieManagement.TMDB.Api/Services/IStatisticsService.cs
src/MovieManagement.TMDB.Api/Services/PersonService.cs
src/MovieManagement.TMDB.Api/Services/SearchService.cs
src/MovieManagement.TMDB.Api/Services/StatisticsService.cs
src/MovieManagement/Pages/SearchResults/SearchResults.razor.cs

Added Get MovieWithHighestRevenue by year or if there is no year, it will display an overall set for all years

SEP6-46: Added GetMovieWithHighestRevenueByYear

---

src/MovieManagement.Database/Repositories/IRatingRepository.cs
src/MovieManagement.Database/Repositories/IUserRepository.cs
src/MovieManagement.Database/Repositories/RatingRepository.cs
src/MovieManagement.Database/Repositories/UserRepository.cs
src/MovieManagement.Functions/Dtos/GetRatingDto.cs
src/MovieManagement.Functions/Dtos/MovieRatingDto.cs
src/MovieManagement.Functions/Ratings/GetMovieRating.cs
src/MovieManagement.Functions/Services/IRatingService.cs
src/MovieManagement.Functions/Services/IUserService.cs
src/MovieManagement.Functions/Services/RatingService.cs
src/MovieManagement.Functions/Services/UserService.cs
src/MovieManagement.Functions/Startup.cs
src/MovieManagement.Functions/Validators/GetRatingDtoValidator.cs

Added username to come with all ratings of a movie, also handles null values and throws an error on no movie provided

SEP6-22: Get ratings with username

---

src/MovieManagement.TMDB.Api/Services/IStatisticsService.cs
src/MovieManagement.TMDB.Api/Services/StatisticsService.cs

Added endpoint for most popular movies of an actor, when the actor's id is supplied

SEP6-45: Most popular movies of an actor

---

src/MovieManagement/Services/AzureService.cs

Remove host key

---

src/MovieManagement.Functions/MovieList/AddMovieList.cs
src/MovieManagement.Functions/MovieList/AddMovieToMovieList.cs
src/MovieManagement.Functions/MovieList/DeleteMovieFromMovieList.cs
src/MovieManagement.Functions/Startup.cs
src/MovieManagement.Functions/Users/EditUser.cs
src/MovieManagement.Functions/Users/LoginUser.cs
src/MovieManagement.Functions/Users/RegisterUser.cs

refactor error logging and add missing validator

---

src/MovieManagement/FunctionDtos/MovieListDto.cs
src/MovieManagement/Pages/MovieLists/CustomMovieList.razor
src/MovieManagement/Pages/MovieLists/CustomMovieList.razor.cs
src/MovieManagement/Pages/_Layout.cshtml
src/MovieManagement/Services/MovieListService.cs
src/MovieManagement/ViewModels/Index/MovieListViewModel.cs
src/MovieManagement/ViewModels/Index/MovieViewModel.cs

SEP6-115: Fix bugs in custom lists

---

src/MovieManagement/FunctionDtos/MovieDto.cs
src/MovieManagement/FunctionDtos/ReviewResponseDto.cs

Fix missing genres and incorrect json name

---

README.md
src/MovieManagement.Domain/Models/TMDB/MovieList.cs
src/MovieManagement.Functions/Validators/GenreListValidator.cs
src/MovieManagement.TMDB.Api/Mappers/MovieMapper.cs
src/MovieManagement/Pages/MovieDetails/MovieDetails.razor
src/MovieManagement/Pages/MovieDetails/MovieDetails.razor.cs
src/MovieManagement/Pages/MovieDetails/MovieDetails.razor.css
src/MovieManagement/ViewModels/MovieDetails/MovieDetailsCrewViewModel.cs
src/MovieManagement/ViewModels/MovieDetails/MovieDetailsViewModel.cs

- Added list of directors on movie details
- Unnecessary attributes removed
- Validator no longer asks for at least 1 genre

Sep6 135 bug fixes

---

src/MovieManagement.Domain/Models/TMDB/Movie.cs
src/MovieManagement.Domain/Models/TMDB/Person.cs
src/MovieManagement.Functions/Dtos/MovieListDto.cs
src/MovieManagement.TMDB.Api/Dtos/GenreListDto.cs
src/MovieManagement.TMDB.Api/Dtos/MovieDto.cs
src/MovieManagement.TMDB.Api/Dtos/PersonDto.cs
src/MovieManagement.TMDB.Api/Mappers/MovieMapper.cs
src/MovieManagement/Components/MovieLists/AddMovieToList.razor
src/MovieManagement/Components/MovieLists/AddMovieToList.razor.cs
src/MovieManagement/Components/MovieLists/AddMovieToList.razor.css
src/MovieManagement/FunctionDtos/MovieDto.cs
src/MovieManagement/Models/MovieModel.cs
src/MovieManagement/Pages/MovieDetails/MovieDetails.razor
src/MovieManagement/Pages/MovieLists/CustomMovieList.razor.cs
src/MovieManagement/Pages/Statistics/HighestRevenueMovies.razor
src/MovieManagement/Pages/Statistics/HighestRevenueMovies.razor.cs
src/MovieManagement/Pages/Statistics/HighestRevenueMovies.razor.css
src/MovieManagement/Services/CombinedRatingService.cs
src/MovieManagement/Services/ICombinedRatingService.cs
src/MovieManagement/Services/IMovieListService.cs
src/MovieManagement/Services/MovieListService.cs
src/MovieManagement/Shared/NavMenu.razor
src/MovieManagement/Shared/Sidebar.razor.cs
src/MovieManagement/ViewModels/Index/MovieViewModel.cs
src/MovieManagement/ViewModels/MovieDetails/MovieDetailsViewModel.cs
src/MovieManagement/ViewModels/PersonDetails/PersonViewModel.cs
src/MovieManagement/wwwroot/css/site.css

Sep6 130 highest revenue year

---

src/MovieManagement/Components/MovieCard.razor
src/MovieManagement/Components/MovieCard.razor.cs
src/MovieManagement/Components/MovieCard.razor.css
src/MovieManagement/Pages/Statistics/HighestRatingMovies.razor
src/MovieManagement/Pages/Statistics/HighestRevenueMovies.razor
src/MovieManagement/Pages/Statistics/HighestRevenueMovies.razor.cs
src/MovieManagement/Pages/Statistics/RatingsByGenre.razor
src/MovieManagement/Services/AzureService.cs
src/MovieManagement/Shared/NavMenu.razor
src/MovieManagement/ViewModels/Index/MovieViewModel.cs
src/MovieManagement/ViewModels/Index/MoviesViewModel.cs

Add vote count to statistics movie card

---

src/MovieManagement.Database/Repositories/ActorRepository.cs
src/MovieManagement.Database/Repositories/IActorRepository.cs
src/MovieManagement.Database/Repositories/MovieActorRepository.cs
src/MovieManagement.Functions/Dtos/GenderDistributionInMainRolesDto.cs
src/MovieManagement.Functions/Services/IStatisticsService.cs
src/MovieManagement.Functions/Services/StatisticsService.cs
src/MovieManagement.Functions/Statistics/DistributionOfGenderInMainRoles.cs
src/MovieManagement/Config/AzureFunctionsConfig.cs
src/MovieManagement/appsettings.json

Function for statistics for the distribution of genders for main actors in movies by genre or of all time
https://via-group2.atlassian.net/browse/SEP6-136

Sep6 136 gender distribution for main roles by genre

---

src/MovieManagement.Functions/Validators/GenreDtoValidator.cs
test/MovieManagement.Test/GlobalUsings.cs
test/MovieManagement.Test/MovieManagement.Test.csproj
test/MovieManagement.Test/MovieTests/ValidatorTests.cs

Unit tests for validators
NOTE: 
In case people wonder why I have used usings insted of global, because there are different models with same name and it is already referencing the TMDB. API so I had to use specific usings there :)

SEP6-137: Unit tests for validators

---

src/MovieManagement.Database/Repositories/ActorRepository.cs
src/MovieManagement/Components/AgeDistributionChart.razor
src/MovieManagement/Components/AgeDistributionChart.razor.cs
src/MovieManagement/Components/Reviews/ReviewsView.razor.cs
src/MovieManagement/FunctionDtos/AgeDistributionInMovieDto.cs
src/MovieManagement/GlobalUsings.cs
src/MovieManagement/Models/AgeDistributionModel.cs
src/MovieManagement/Pages/MovieDetails/MovieDetails.razor
src/MovieManagement/Pages/Statistics/RatingsByGenre.razor.cs
src/MovieManagement/Services/IStatsService.cs
src/MovieManagement/Services/StatsService.cs
src/MovieManagement/ViewModels/Statistics/AgeDistributionViewModel.cs

SEP6-124: Age distribution in a movie

---

src/MovieManagement/Models/GenderDistributionModel.cs
src/MovieManagement/Pages/Statistics/GenderDistributionByGenre.razor
src/MovieManagement/Pages/Statistics/GenderDistributionByGenre.razor.cs
src/MovieManagement/Pages/Statistics/GenderDistributionByGenre.razor.css
src/MovieManagement/Pages/Statistics/RatingsByGenre.razor
src/MovieManagement/Services/IStatsService.cs
src/MovieManagement/Services/StatsService.cs
src/MovieManagement/Shared/NavMenu.razor
src/MovieManagement/ViewModels/Statistics/GenderByGenreViewModel.cs

SEP6-139: Gender distribution FE

---

src/MovieManagement/Pages/Statistics/GenderDistributionByGenre.razor
src/MovieManagement/Shared/NavMenu.razor

fix path for gender statistics

---

src/MovieManagement/Shared/NavMenu.razor

remove typo

---

src/MovieManagement/Pages/_Layout.cshtml

change radzen style sheet

---

src/MovieManagement/Components/AgeDistributionChart.razor
src/MovieManagement/Pages/Statistics/GenderDistributionByGenre.razor
src/MovieManagement/Pages/Statistics/RatingsByGenre.razor
src/MovieManagement/wwwroot/css/site.css

fix bar chart labels

---

src/MovieManagement.Functions/Actors/AddActorListForMovie.cs
src/MovieManagement.Functions/Services/StatisticsService.cs
src/MovieManagement.Functions/Startup.cs
src/MovieManagement.Functions/Validators/ActorValidator.cs
src/MovieManagement.Functions/Validators/AddMovieActorValidator.cs

Overall changes
Refactored the Statistics service to add tags for all ages and ordered them by keys
Added Actor Validator because I forgot about them the first time

Sep6 142 be refactor

---

src/MovieManagement/Program.cs

Removed db section from Program

SEP6-142: refactor Program

---

README.md

Update README.md with names

---

.github/workflows/build_blazor_application.yml
.github/workflows/main_moviemanagementfunctions.yml
.github/workflows/main_sep6group2moviemanagement.yml

Change workflow files

---

src/MovieManagement/Pages/PersonDetails/PersonDetails.razor.cs

keep the person details if adding fails
